# Generated by Django 5.1 on 2024-09-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('DonorID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=25)),
                ('passWord', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('phoneNumber', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='paymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Method', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('SponsorID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('phoneNumber', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('DonorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('CamID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=500)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('goalAmount', models.IntegerField(max_length=25)),
                ('balanceAmount', models.IntegerField(max_length=25)),
                ('SponsorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Textmessage',
            fields=[
                ('MesID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context', models.CharField(max_length=25)),
                ('CamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField(max_length=25)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('DonorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.donor')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.paymentmethod')),
            ],
        ),
    ]
